"""empty message

Revision ID: 749421166b6f
Revises: 9962bfe38479
Create Date: 2021-09-05 14:44:11.377781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749421166b6f'
down_revision = '9962bfe38479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grab_cut_mask', sa.Column('interactionrecord_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grab_cut_mask', 'interactionrecord_id')
    # ### end Alembic commands ###
