"""empty message

Revision ID: bc761a3ab8a2
Revises: cbd7a88aacce
Create Date: 2021-07-12 12:34:36.290362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bc761a3ab8a2'
down_revision = 'cbd7a88aacce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grab_cut_interaction_model',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('annotated_pixels', sa.Integer(), nullable=True),
    sa.Column('foreground_pixels', sa.Integer(), nullable=True),
    sa.Column('background_pixels', sa.Integer(), nullable=True),
    sa.Column('scribbles', sa.Integer(), nullable=True),
    sa.Column('foreground_scribbles', sa.Integer(), nullable=True),
    sa.Column('background_scribbles', sa.Integer(), nullable=True),
    sa.Column('submissions', sa.Integer(), nullable=True),
    sa.Column('first_submission_time', sa.DateTime(), nullable=True),
    sa.Column('last_submission_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('todo_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_model',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='todo_model_pkey')
    )
    op.drop_table('grab_cut_interaction_model')
    # ### end Alembic commands ###
