"""empty message

Revision ID: df638ad98491
Revises: bc761a3ab8a2
Create Date: 2021-08-19 12:01:03.606454

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'df638ad98491'
down_revision = 'bc761a3ab8a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grab_cut_interaction_model', sa.Column('submission_counter', sa.Integer(), nullable=True))
    op.add_column('grab_cut_interaction_model', sa.Column('first_interaction_time', sa.DateTime(), nullable=True))
    op.add_column('grab_cut_interaction_model', sa.Column('submission_time', sa.DateTime(), nullable=True))
    op.drop_column('grab_cut_interaction_model', 'last_submission_time')
    op.drop_column('grab_cut_interaction_model', 'submissions')
    op.drop_column('grab_cut_interaction_model', 'first_submission_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grab_cut_interaction_model', sa.Column('first_submission_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('grab_cut_interaction_model', sa.Column('submissions', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('grab_cut_interaction_model', sa.Column('last_submission_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('grab_cut_interaction_model', 'submission_time')
    op.drop_column('grab_cut_interaction_model', 'first_interaction_time')
    op.drop_column('grab_cut_interaction_model', 'submission_counter')
    # ### end Alembic commands ###
